### ISSUE TITLE
Browse Table context menu option doesn't browse selected table

### ISSUE THREAD

**Issue by jadeade** [sqlitebrowser/sqlitebrowser#1051]
### Details for the issue

Browse Table context menu option doesn't browse selected table, it just switches to "Browse Data" tab and nothing happens, data grid is empty and table combo just shows first table in the list

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: (Win8x64)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: but didn't find a thing

**Comment by justinclift** [comment]
Oh... I think that's a bug we fixed a while ago.

Would you be ok to try the latest nightly build, just to confirm? :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by jadeade** [comment]
Hi! yes it seems to be working on latest nightly build, just tested and works, what a coincidence cos this has been happening for a while and updated at least twice hoping that it was already working and decided to report after 3.9.1 haha. I should have report it before, but I am a real procrastinator :)

Thank you for the great work!

**Comment by justinclift** [comment]
Heh Heh Heh, it's all good @jadeade. :smile:

**Comment by SuziQu** [comment]
I have just downloaded version 3.11.1 and this is still occurring but seems to only happen with the first table I browse.  It picks up the next table in the list.

Great product.

**Comment by justinclift** [comment]
Oh, that's not good.  Which OS are you using, and does it happen every time?  eg is it repeatable?

**Comment by SuziQu** [comment]
Hi Justin

Its been happening for a long time now, over 2 years I reckon and when I
downloaded the latest version, I checked and it is still misbehaving, so
thought I'd report it, its only mildly annoying.  I thought it might be a
trigger happy mouse but I think after this amount of time, its probably a
small bug.  I'm using macOS 10.13.6.

Many thanks
Sue

**Comment by justinclift** [comment]
No worries @SuziQu, thanks for pointing it out. :smile:

**Comment by SuziQu** [comment]
Sorry, didn't answer all your questions.  Yes it is happening regularly but
seems to be on the first dropdown of the control, after that it seems to
behave.  It is repeatable.

**Comment by mgrojo** [comment]
@SuziQu I could not reproduce this using [v3.13.0](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.13.0). Could you please confirm or otherwise provide the detailed steps to reproduce it using v3.13.0?
