### ISSUE TITLE
Compile failure for Windows nightlies

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1471]
The windows nightlies have been failing to compile for the last two days, and I've just now had time to take a look.

The problem seems to be a change in the CMakeLists.txt:

```
C:\git_repos\sqlitebrowser\release-sqlite-win32>cmake -G "Visual Studio 12 2013" -Wno-dev ..  1>>C:\\dev\\nightlies.log

CMake Error at CMakeLists.txt:353 (add_executable):
  The target name "DB Browser for SQLite" is reserved or not valid for
  certain CMake features, such as generator expressions, and may result in
  undefined behavior.


CMake Error at CMakeLists.txt:361 (add_dependencies):
  Cannot add target-level dependencies to non-existent target "DB Browser for
  SQLite".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.


CMake Error at CMakeLists.txt:363 (add_dependencies):
  Cannot add target-level dependencies to non-existent target "DB Browser for
  SQLite".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.


CMake Error at CMakeLists.txt:366 (add_dependencies):
  Cannot add target-level dependencies to non-existent target "DB Browser for
  SQLite".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.


CMake Error at CMakeLists.txt:382 (target_link_libraries):
  Cannot specify link libraries for target "DB Browser for SQLite" which is
  not built by this project.

```

The line numbers given don't seem to match up to any recent CMakeLists.txt change, so I'm not 100% sure what the problem is.  Possibly related to 961141ec36a88c6c53a3262ae77da14f46c8f4c0 though, as that change matches up with the start of the compile failure.

Anyone have ideas on what to try?

**Comment by MKleusberg** [comment]
I think this is because of the spaces in the project name. Because we changed the cmake version from 2.x to 3.x [this new policy](https://cmake.org/cmake/help/v3.11/policy/CMP0037.html) is taking effect now. The other OSs didn't produce errors because the project name there is sqlitebrowser, without any spaces.

Shall we rename the project to ```DB_Browser_for_SQLite``` or back to ```sqlitebrowser``` on Windows?

**Comment by justinclift** [comment]
I guess we'll have to.  We'll need to ensure the final resulting binary gets renamed to "DB Browser for SQLite.exe", but that might just mean adding a manual rename step somewhere appropriate. :smile:

**Comment by MKleusberg** [comment]
Looks like there is a way to have different names for the project and the executable in cmake. Let's try if that works - I've just pushed a commit for this :smile:

**Comment by justinclift** [comment]
Just kicked off a new nightly build manually to see if it works... and it's still erroring out.  Just the one failure this time though:

```
C:\git_repos\sqlitebrowser\release-sqlite-win32>cmake -G "Visual Studio 12 2013" -Wno-dev ..  1>>C:\\dev\\nightlies.log

CMake Error at CMakeLists.txt:34 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  sqlitebrowser
```

**Comment by justinclift** [comment]
Hmmm, I wonder if something like this will work:

```
set(OUTPUT_NAME "DB Browser for SQLite.exe")
```

I'll give that a go in a temp branch, and see what happens.

**Comment by justinclift** [comment]
Hmmm, well that doesn't error out with CMake now, but it's still not happy.  Still investigating.

As an aside, this error is showing up in the MSVC console now when compiling manually through MSVC:

```
6>C:\git_repos\sqlitebrowser\src\sqltextedit.cpp(64): error C3409: empty attribute block is not allowed
6>C:\git_repos\sqlitebrowser\src\sqltextedit.cpp(64): error C2143: syntax error : missing ']' before '['
6>C:\git_repos\sqlitebrowser\src\sqltextedit.cpp(64): error C2653: 'clang' : is not a class or namespace name
6>C:\git_repos\sqlitebrowser\src\sqltextedit.cpp(64): error C2337: 'fallthrough' : attribute not found
6>C:\git_repos\sqlitebrowser\src\sqltextedit.cpp(64): error C2143: syntax error : missing ';' before ']
```

**Comment by justinclift** [comment]
Ahhh, yep.  That clang suppression line is definitely breaking the build.  Just tested things without it, and the compile happens... although the output name is still getting done as "sqlitebrowser.org" atm.  Working on solving that next.

**Comment by justinclift** [comment]
Initial working fix in 9a76537aa4084e5ea3fb0ac81d9efa5dc84206ff.  I'll wait to see the nightly build fully run successfully by itself before closing this though. :smile:

**Comment by justinclift** [comment]
Turned out I'd just forgotten to update the new Qt path in the msi building bit.  That's now, done.

The 64-bit .exe's being generated though aren't good.  Weirdly, it appears to be a problem with Win7's dos based COPY command.  Copying the "good" win64 .exe from one location to the eventual dir it's uploaded from is resulting in only the first few mb of the file being copied to the destination file.  Consistently.  Seen this one before, and the work was to copy it to a temp location using a slightly different method, then doing a 2nd copy to get it to the right spot.  That's not working this time.  Bizarre.  Still investigating for a workaround.

**Comment by justinclift** [comment]
Oops, no.  It's not the copy going wrong for the 64 bit ones.  Something else is wrong before that...

**Comment by justinclift** [comment]
No change.  Doesn't seem to be caused by the Qt version.

Instead of spending further hours trying to figure this out, let's just drop the .exe's.  We'd been planning to move to .msi's only anyway.

**Comment by justinclift** [comment]
k, things seem to be working acceptably now (.msi's only).  For Windows 32-bit, the Qt version is still 5.7.  For the 64-bit version, we're now using 5.10.1.

**Comment by jungle-boogie** [comment]
Hi,

Thanks for getting the builds working again.

I've installed the latest x64 bit build, but the UI is quite a bit different than I normally saw with the exe build. Here's a picture: https://imgur.com/a/WQFIr9M
For a reminder of how it used to look, see this video:
https://www.youtube.com/watch?v=CW739mop1Nc

Is this intentional?

**Comment by MKleusberg** [comment]
No, this is definitely not intentional. Looks like the manifest file is missing or something.

**Comment by justinclift** [comment]
Hmmm, I wonder if it's something in the new Qt version?

@jungle-boogie Are the .msi builds from (say) 1 week ago ok?

**Comment by karim** [comment]
Last working version is from July 10 (Qt 5.7.1). Versions from July 13 onward are not working (Qt 5.10.1). No July 11 and 12 versions, so I'm guessing this is when it started to fail.

I get the same GUI look as in @jungle-boogie screenshot. Also this one..

![error](https://user-images.githubusercontent.com/8761081/42729499-8aa97f00-87da-11e8-8138-0e0ef98aed20.jpg)

**Comment by justinclift** [comment]
Interesting.  I'll revert the Qt version back to 5.7, which will hopefully solve the weirdness.

I'd totally forgotten about that "The network is not accessible" warning dialog.  We hit that the last time I experiemented with Qt 5.10.1 as well.

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/pull/1400#issuecomment-393891973

We're going to need to figure out what the problem with Qt 5.10.1 is at some point, as we want to move past that to Qt 5.11.x.  Qt 5.11 apparently adds important accessibility things (eg for screen readers for the visually impaired), which would be useful for some people.

**Comment by justinclift** [comment]
As a data point, looking through these might help us figure out what's going wrong with Qt versions later than 5.7:

* https://wiki.qt.io/New_Features_in_Qt_5.8
* https://wiki.qt.io/New_Features_in_Qt_5.9
* https://wiki.qt.io/New_Features_in_Qt_5.10

One of the things mentioned for 5.10 is "OpenSSL 1.1 back-end".  Maybe it requires OpenSSL 1.1 at a minimum now?

Hmmm... instead of reverting back to 5.7, I'll revert the 64-bit installer back to 5.9.  If either the visual look problem or the network warning one goes away, then we know it was something introduced in 5.10.  Should help us narrow down where to look.

**Comment by justinclift** [comment]
I've just changed the nightlies build server to use Qt 5.9.6 for the Win64 builds, and manually launched the nightly build script.  We should have something to test in about 45 minutes or so.

**Comment by justinclift** [comment]
@jungle-boogie @karim Would you have time to check today's nightlie's again?  They're now rebuilt using Qt 5.9, so it'll be interesting to see if that makes a difference. :smile:

**Comment by karim** [comment]
Latest nightly (Qt 5.9.6) fixed the GUI look, but not the network error.

**Comment by justinclift** [comment]
Thanks, that's useful info.  I'll drop it back to Qt 5.8, and we can see if the network error still shows up.

Looks like it's not a "Must use OpenSSL 1.1" thing then too.

**Comment by karim** [comment]
One odd thing with July 15 build is this..

![db4s](https://user-images.githubusercontent.com/8761081/42734903-ebd9aa7c-884b-11e8-98ac-086756575688.jpg)

The right side where you can have SQL log, Plot, and DB Schema is always there. In earlier version, if you are not using/showing them it would stretch the main view to the whole window, like this..

![db4s2](https://user-images.githubusercontent.com/8761081/42734936-6a78199a-884c-11e8-9523-dfec271ad41d.jpg)

First screenshot is July 15 build (Qt 5.9.6). Second screenshot is July 14 (Qt 5.10.1).

**Comment by justinclift** [comment]
Weird.  Kind of seems like a Qt 5.9 bug, as that doesn't happen with 5.7 nor 5.10.1.

**Comment by justinclift** [comment]
k, new Windows nightlies have just been uploaded.  These ones are based on Qt 5.8.

**Comment by MKleusberg** [comment]
The style seems like it's easy enough to fix: we probably only need to add the ```styles\qwindowsvistastyle.dll``` file to the plugin directory. See [here](https://doc.qt.io/qt-5/windows-deployment.html#creating-the-application-package) and [here](https://forum.qt.io/topic/86777/missing-qapplication-styles-in-qt-5-10-0/10).

**Comment by justinclift** [comment]
Cool. :smile:

I'm kind of suspecting the network error dialog might be caused by some missing new Qt dll too. :smile:

**Comment by jungle-boogie** [comment]
With 16 July download, I cannot open DB Browser:
The program can't start because Qt5Network.dll is missing from your computer. Try reinstalling the program to fix this problem.

**Comment by jungle-boogie** [comment]
Ah, removing and reinstalling actually fixed it!

**Comment by jungle-boogie** [comment]
I see the QT version is currently 5.8.

**Comment by justinclift** [comment]
Sounds like the 16th July nightly is in decent shape then.  Guess that means the weird network problem dialog is due to something introduced in Qt 5.9.  It should show up in the [5.9 release notes](https://wiki.qt.io/New_Features_in_Qt_5.9) then.

**Comment by karim** [comment]
> With 16 July download, I cannot open DB Browser:
> The program can't start because Qt5Network.dll is missing from your computer. Try reinstalling the program to fix this problem.

I think I have an idea why..

1. Current installed app is using Qt 5.9 DLLs, but new version is using Qt 5.8 DLLs.
2. Installer detected that some installed files are newer (5.9) than the ones being installed (5.8).
3. Installer doesn't install these DLLs since you have a newer version of them already (default action).
4. Trying to run the app will fail cause these files are missing now.

Reinstalling or repairing the installer should fix this. Right-click on the .msi file and select **Repair** will do it.

@justinclift Yes, you are right. 16th July build fixed both (GUI and network) problems for me. Also I don't get this grey area on the right side as I mentioned in my earlier comment. Thanks :smile:

**Comment by justinclift** [comment]
Cool.  Guess this issue can be closed again now. :smile:
