### ISSUE TITLE
HDPI scaling on fedora 28

### ISSUE THREAD

**Issue by QtCat2** [sqlitebrowser/sqlitebrowser#1711]
Details for the issue
--------------------
![sc](https://user-images.githubusercontent.com/46658878/51217903-108ad200-18f8-11e9-81d0-6d04ccf9d480.png)
#### What did you do?
Installed sqlitebrowser from Gnome Software 3.28.2

#### What did you expect to see?
Properly scale application

#### What did you see instead?
Unscaled application

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @QtCat2.  We're close to making a new release, with all of the improvements since that 3.10.1 release you're seeing.

Are you any good at compiling things from source code?  If you are, our instructions for building on Fedora are here:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#centos--fedora-linux

It'd be useful to see if the same HiDPI problem still happens with that.  In theory, it should be fixed. :smile:

**Comment by QtCat2** [comment]
Thanks for the quick response!

After reading your comment I tried building from source, but it still does not scale up. Here is the result.
![sc2](https://user-images.githubusercontent.com/46658878/51281220-c7965480-19af-11e9-8c67-65c151e6c3fb.png)

**Comment by justinclift** [comment]
Ugh.  Well, that's not good. :wink:

We'll need to get that fixed.  It's not urgent for the next release - should be out any day now - so it'll have to come in the one after that.  And in the nightly builds from whenever we figure out how to fix it.

At a guess, probably none of our developers are using a HiDPI monitor.  So, no-one's been annoyed by this enough to figure out how to fix it.

Hmm... on that note, are you any good at C/C++ programming?  We're definitely open to patches for improving things. :grin:

**Comment by QtCat2** [comment]
@chrisjlocke  The slight increase in size you noticed was the embedded image in the browser web-page. In relation to the first post it looks like an improvement. However, the image scale is actually the same. I edited the post remove the ambiguity.

@justinclift I don't code C/C++ yet unfortunately, I would sure have a look at it if I could. I'm kind  of a visual person. So figuring out databases with a GUI is a must. An opportunity to get involved!

**Comment by chrisjlocke** [comment]
> However, the image scale is actually the same

Dang.  Apologies.

**Comment by QtCat2** [comment]
It works on Fedora 29. Cheers guys!

**Comment by chrisjlocke** [comment]
So its more of an issue with Fedora 28?  Interesting.  Thanks for reporting back.
