### ISSUE TITLE
Application hangs when plotting lots of NULL values

### ISSUE THREAD

**Issue by wrenoud** [sqlitebrowser/sqlitebrowser#1977]
Details for the issue
--------------------

#### What did you do?

Tried to plot 2 fields on the Y axis, one of which has mostly NULL values. About 300 rows in total

#### What did you expect to see?

A plot

#### What did you see instead?

The application hangs for a long time. It ultimately plots, but NULL values appear to be infinite vertical lines and any redraw (zoom/pan) hangs again.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [X] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by wrenoud** [comment]
A workaround for me is to replace NULL values with 0 in a query using `ifnull("my_column", 0)`

**Comment by wrenoud** [comment]
@sky5walk `null` is an appropriate null value. I was noting that replacing the null values with a number prevented the application hang. A "correct" replacement is going to be data set specific. And correct me if I'm wrong, but I know of no way to prevent a value from being plotted when you try to plot 2 columns on the y axis.

**Comment by wrenoud** [comment]
@sky5walk I think you misunderstood my bug report. I've updated the title and I will elaborate. I have essential 3 columns

|index|value1|value2|
|------|-------|-------|
|1|3|_NULL_|
|2|7|_NULL_|
|3|7|1|

I wish to see plots for both `value1` and `value2` vs `index` on the same plot. Omitting null values for `value2` is a mostly useless plot for me as I won't see most of `value1`. I'm even OK with the current choice of drawing an infinite line for _NULL_, but that seems to perform very poory if there are more than a couple _NULL_ values.

**Comment by MKleusberg** [comment]
I just gave this a quick try and couldn't reproduce it. Is there maybe something else I have to do to make it hang, like sort order, data types, etc.?

I do see however how NULL values are rendered in a weird way, it just doesn't seem to affect the performance for me. To make it render correctly we would have to decide what to do with NULL values? Skip them or treat them as 0, make it configurable, or something else altogether?

**Comment by mgrojo** [comment]
We are in fact using NULL in a way expected by our plot library:

https://www.qcustomplot.com/documentation/classQCPGraph.html
> Gaps in the graph line can be created by adding data points with NaN as value (qQNaN() or std::numeric_limits<double>::quiet_NaN()) in between the two data points that shall be separated.

I think inserting gaps is also the best way to handle those NULL values.

> It ultimately plots, but NULL values appear to be infinite vertical lines

That doesn't match with the expectation. It should produce a gap in the curve. Can you provide a screenshot?

Regarding the performance problem, does it help decreasing the "Prefecht block size" in "Preferences > Database", @wrenoud? What is the value of "lots" in "lots of NULL values" :smile: ? Shouldn't matter if replacing them with zeros solve the problem, anyway. Maybe treating those gaps is costly for the plot library. Just guessing.

**Comment by mgrojo** [comment]
> @sky5walk I think you misunderstood my bug report. I've updated the title and I will elaborate. I have essential 3 columns
> index 	value1 	value2
> 1 	3 	_NULL_
> 2 	7 	_NULL_
> 3 	7 	1
> 
> I wish to see plots for both `value1` and `value2` vs `index` on the same plot. Omitting null values for `value2` is a mostly useless plot for me as I won't see most of `value1`. I'm even OK with the current choice of drawing an infinite line for _NULL_, but that seems to perform very poory if there are more than a couple _NULL_ values.

With those values, I get this plot (some zoom out applied):

![imagen](https://user-images.githubusercontent.com/13812910/63715220-9d5d1d00-c843-11e9-93c6-0356ed451afc.png)

Isn't the same for you?

**Comment by MKleusberg** [comment]
@mgrojo I get the same plot. However, for another test case with ~2000 rows and about one third of them NULL I get this (there is definitely no value < 10000, so the extra thin line is going nowhere):
![test](https://user-images.githubusercontent.com/3153504/63716656-ca5eff00-c846-11e9-8873-bce5743ca39b.png)
It depends on the sort order of the data (as far as I can tell it doesn't happen when most of the NULL values are in one place; but it does happen if numbers and NULL values are mixed a lot) and on the zoom level. It's also impossible to follow the thin extra lines because they always disappear for me whenever I drag the plot around.

**Comment by mgrojo** [comment]
Maybe the problems are with NULL values in X? We are not checking for NULL in that axis and they seem to be translated to 0, probably by toDouble().  I've committed a change that also applies that logic to the x axis. I think both axes should be treated equally, independently of whether we should make the logic configurable, which I'm not sure it would be useful.

@MKleusberg and @wrenoud, could you confirm if it gives the expected result with your data, using tomorrow's nightly build?

**Comment by wrenoud** [comment]
Here is an example table that reliably causes the hang for me: https://dbhub.io/wrenoud/asfd.db

I select datetime for the X axis, then selecting either count1 or count2 for Y axis is OK, but selection the other column as the second Y axis the hangs.

I also downloaded and installed the nightly and I still experience this.

**Comment by justinclift** [comment]
> https://dbhub.io/wrenoud/asfd.db

That's giving a "doesn't exist" error.  It's probably still set to private.  If you go into the settings for the database you can set it to public. :smile:

**Comment by wrenoud** [comment]
@mgrojo I saw your comment after posting my comment. I downloaded the 3.11.99 (Aug 27 2019) build, is that the "tomorrow" you're referening to?

**Comment by wrenoud** [comment]
@justinclift, sorry, I thought I had made it public. Should be fixed now.

**Comment by justinclift** [comment]
Thanks @wrenoud. Yep, it can be grabbed by people now. :smile:

**Comment by wrenoud** [comment]
I just realized the thing I wasn't reporting in the case. My line type was set to `Impulse`. Switching to `Line` works just fine.

**Comment by wrenoud** [comment]
This is what I meant by the "infinite vertical line"
![image](https://user-images.githubusercontent.com/2761756/63758639-61b26980-c8bc-11e9-890c-b959c066aaf7.png)

Even with just the 2 `NULL` values it's super slow to zoom/pan the Impulse plot.

**Comment by mgrojo** [comment]
> I just realized the thing I wasn't reporting in the case. My line type was set to Impulse. Switching to Line works just fine.

Ok, I see now the plot drawing problem  setting the Impulse line type. I don't know if we can do something. It seems that in this case the NULL/NaN feature is not implemented in the same way as in the other cases. It's true that a "gap" does not make sense with those line types, so maybe the plot library is not expecting them in those cases.

> Even with just the 2 `NULL` values it's super slow to zoom/pan the Impulse plot.

I don't appreciate the slowness, but it is another hint about not expecting the gaps in this case.

We'll have to think what we want to do for this combination.
