### ISSUE TITLE
Update tables in "execute SQL" tab

### ISSUE THREAD

**Issue by hko-gh** [sqlitebrowser/sqlitebrowser#205]
First: great piece of software!
Second: The auto-completion is not updated when SQL statements are executed "Execute SQL" tab. So when I add or remove tables there, auto-completion is not up to date.

**Comment by justinclift** [comment]
Aha, sounds like a bug.  Which OS, and which version of DB4S (our acronym) are you using? :smile:

**Comment by hko-gh** [comment]
Win7 64bit using the sqlitebrowser 32bit win installer. Noticed that behaviour in the last 3 versions (3.4.0, 3.5.0 and 3.5.1)

**Comment by justinclift** [comment]
@MKleusberg @rp- Any idea how easy a fix this would be?  It sounds like a function call needs to be run after each Execute SQL command.  ?

**Comment by rp-** [comment]
shouldn't be to hard, just a call to update the stored tables/columns in the texteditor widget after a execute sql was done

**Comment by justinclift** [comment]
@MKleusberg This should be fixed now yeah?

**Comment by MKleusberg** [comment]
Just tested this with the latest version and it seems to be fixed. No idea when the fix was pushed, sorry for the waiting time :frowning: I'm going to close this issue since it's really old and everything seems to work as expected now. But if any further problems should arise, feel free to reopen this issue :smiley:

**Comment by justinclift** [comment]
@hko-gh Do you have a few minutes to try this out with our latest nightly version, to double check it from your point of view? :smile:

**Comment by hko-gh** [comment]
Sorry, still not working for me. When I rename a table in the 'Database structure' tab, everything works as intended. But when I rename a table manually using the 'Execute SQL' tab, I do not have the correct auto-completion afterwards. (Version 3.9.1. 64-bit Win7)

**Comment by chrisjlocke** [comment]
You need to download one of the nightly builds (usually version 3.9.99) from here:
https://nightlies.sqlitebrowser.org/win64/

eg:
https://nightlies.sqlitebrowser.org/win64/DB%20Browser%20for%20SQLite-2017-01-09-win64.exe

v3.9.1 is our 'last release' which doesn't get automatically updated with fixes, etc.

**Comment by justinclift** [comment]
@hko-gh Did you have a chance to try a recent nightly build?  A lot of improvements have happened since our 3.9.1 release. 😄
