### ISSUE TITLE
Altering table that has a PK, results in an invalid sql statement, unable to save.

### ISSUE THREAD

**Issue by AmroOsama** [sqlitebrowser/sqlitebrowser#2422]
Details for the issue
--------------------
Modifying a table that has a PK, results in an invalid sql statement, thus unable to save the changes.

#### What did you do?
Modify a table 

#### What did you see instead?
Two brackets are add instead of one, resulting in an invalid sql statement, thus applying the structure edit does not work
	PRIMARY KEY([[ID]])

I found where the bug is, as soon as the Modify Table window is opened, the PK Constraint field is added with a bracket, and again added in the SQL statement in the Primary key with brackets again, resulting in double brackets.

Workaround till the bug is fixed:
1- Do your edits to the table
2- Delete the constraint from the constraints tab.
3- Mark the field as PK again.
4- Press OK to save.
![1](https://user-images.githubusercontent.com/44859987/95145885-0f14d380-0785-11eb-958c-dbab9315ee77.png)

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19041) [x86_64]
> using SQLCipher Version 4.4.0 community (based on SQLite 3.31.0)
> and Qt 5.12.8

**Comment by AmroOsama** [comment]
Workaround till the bug is fixed:
1- Do your edits to the table
2- Delete the constraint from the constraints tab.
3- Mark the field as PK again.
4- Press OK to save.

**Comment by justinclift** [comment]
Thanks @AmroOsama, that definitely sounds like a bug.

Any interest in trying out the latest nightly build?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

That has a bunch of bug fixes plus various other improvements in it, and there's a decent chance this bug has already been addressed in that. :smile:

**Comment by AmroOsama** [comment]
@justinclift, Thanks for the Ultra quick reply ;)
Just tried 3.12.1, and even the nightly build you just sent.
The bug is still there unfortunately.

PS: As a fellow Software developer who appreciates marvels, thanks a ton for the work done on this beautiful peace of software!

**Comment by justinclift** [comment]
Oh well, was worth a shot. :shrug:

@MKleusberg This bug sounds like your kind of thing. :smile:

> PS: As a fellow Software developer who appreciates marvels, thanks a ton for the work done on this beautiful peace of software!

You're welcome.  There's a bunch of us, with different areas of interest, so the load is (somewhat) spread around. :smile:

**Comment by chrisjlocke** [comment]
In your examples, where are the square brackets coming into play?  I notice they're not in the top (initial) schema, but are in the bottom.  Also, 'pk' isn't ticked, but the bottom schema notes a primary key... again, using the square brackets.

Have you created this table from an export from a Sql Server database, for example (which loves square brackets)

**Comment by AmroOsama** [comment]
Actually the PK was and should be ticked, 
But after creating the table in the designer and saving, then modifying it, it loads like that,
So that's a bug too ;)

The table was created using the designer, not imported or executed using a statement.

Thanks.

**Comment by chrisjlocke** [comment]
If you click 'Edit' and 'Preferences', then the 'SQL' tab, what value have you got for 'Quotes for Identifiers'.

![image](https://user-images.githubusercontent.com/7872218/95195311-43f94880-07ce-11eb-87bd-ec217cef427a.png)

Do you work with SQL Server databases?  (importing from/exporting to)
While this may be a bug in the parsing of Sql Server schemas, if you set the option to SQLite, all may be better.

**Comment by AmroOsama** [comment]
Mine was set to Square Brackets - Traditional MS SQL Server quotes
but that was the default when I installed the app, I didn't manually change it.

No, I did not import anything from SQL Server.

PS: settings it to double quotes fixed the issue, but I had to remove the constraint one last time.

**Comment by chrisjlocke** [comment]
> but that was the default when I installed the app, 

Interesting.  Was this a clean install of 3.12, or did you have a previous version?

**Comment by AmroOsama** [comment]
I tried a clean install, and it's by default Double quotes,
So I may have changed it a while ago, although I don't think I did.

I previously had 3.11 I guess.
speaking of 3.11, Windows 3.11, a lot of good childhood memories ;)

**Comment by chrisjlocke** [comment]
Glad you got it working.  We've not had thousands of reports on this issue, so ... leads me to believe ... er..... its your own crazy fault! ;)

If you've an Android phone, try out 'Win 98 Simulator' - its a small download but simulates a good number of apps - media player (which does work), browser (which works better than IE4 ever did), Paint, etc.
https://play.google.com/store/apps/details?id=com.lr_soft.windows98simulator&gl=GB

https://i.imgur.com/EyvTkGr.jpg

**Comment by eevleevs** [comment]
> Glad you got it working. We've not had thousands of reports on this issue, so ... leads me to believe ... er..... its your own crazy fault! ;)

Unfortunately same here, on a clean install of 3.12 :-/

**Comment by AmroOsama** [comment]
> Glad you got it working. We've not had thousands of reports on this issue, so ... leads me to believe ... er..... its your own crazy fault! ;)
> 
> If you've an Android phone, try out 'Win 98 Simulator' - its a small download but simulates a good number of apps - media player (which does work), browser (which works better than IE4 ever did), Paint, etc. If you liked Win 3.11, using Win 98 will be ~hours~ minutes of fun.
> https://play.google.com/store/apps/details?id=com.lr_soft.windows98simulator&gl=GB
> 
> https://i.imgur.com/EyvTkGr.jpg

;)

Thanks for the win98 simulator!

**Comment by justinclift** [comment]
@lucydodo Any interest in looking into this one?

**Comment by lucydodo** [comment]
@justinclift Sorry. it's difficult because there are other thing I am dealing with right now. but I'll add it to my to-do list. 😄

**Comment by justinclift** [comment]
No worries.  You don't need to add it to your ToDo list, it was just a question. :smile:

**Comment by lucydodo** [comment]
@AmroOsama btw, I haven't been able to reproduce this bug. Can I get a little more detailed explanation?

**Comment by chrisjlocke** [comment]
In preferences, if you change the 'Quotes for Identifiers' option to 'Square brackets', then you can't modify tables.

![image](https://user-images.githubusercontent.com/7872218/97070230-b93a8b00-15ce-11eb-962c-fe0a19f9440b.png)

If the table has a primary key, the resulting SQL is invalid.

DB4S cannot parse the schema, so the primary key is unchecked

![image](https://user-images.githubusercontent.com/7872218/97070273-11718d00-15cf-11eb-8c2b-507c34d57e45.png)

If you check the primary key checkbox, the issue is compounded (duplicated) with extra invalid SQL added.

**Comment by MKleusberg** [comment]
Thanks for the detailed analysis everybody 👍 This issue should be fixed in the next nightly build. @AmroOsama Can you try the next nightly and check if it's working for you?

**Comment by AmroOsama** [comment]
> Thanks for the detailed analysis everybody 👍 This issue should be fixed in the next nightly build. @AmroOsama Can you try the next nightly and check if it's working for you?

Thanks you!, 
FYI, unfortunately the Nightly build I found was a dmg file only, I only have Windows at the moment.
Last nightly build for windows was on October 15.

**Comment by chrisjlocke** [comment]
Aah thanks for reporting that - they should be newer than that...
