### ISSUE TITLE
First click on table does not activate buttons in Database Structure tab

### ISSUE THREAD

**Issue by ediril** [sqlitebrowser/sqlitebrowser#2528]
I found another issue with the nightly build. Go to "Database Structure" tab, click on a table. Notice that "Modify Table" and "Delete Table" buttons do not get activated. Click again on a different table. This time they do get activated.

I would expect the first click on a table should activate the buttons. 

Note that this works in version 3.12.1

**Comment by chrisjlocke** [comment]
Thanks for the report!

**Comment by chrisjlocke** [comment]
It's actually a little more bizarre than that.  Open a database.  Tab is usually on the structure view.  The buttons are disabled as you explain.  Right click on a table, and they appear.  Open a database again.  Buttons are now active, but the table isn't 'selected'. Select the table, and the buttons are now disabled.

As this happens in the nightlies (and the codebase from the nightlies and the 'master' are different - bits are just cherry-picked from the nightlies to master as required) this may be a weird thing that may not get fixed as it's tied to a raft of other 'quirks'...

**Comment by MKleusberg** [comment]
Hmm, could be a Qt version thing. Either way, this should be fixed in tomorrow's nightly build. Can you give that a try, @ediril? :smile:

**Comment by ediril** [comment]
Sure, but looks like the nightly build hasn't updated since 21-Jan-2021 

<img width="713" alt="Screen Shot 2021-01-24 at 4 56 58 AM" src="https://user-images.githubusercontent.com/5505693/105626880-ff3b0100-5e00-11eb-9021-176c7e1219b6.png">

**Comment by chrisjlocke** [comment]
Yup - we're on it (https://github.com/sqlitebrowser/sqlitebrowser/issues/2554).  Unfortunately we've had to let the guy who twiddles the knobs on our nightlies some time off.  We're going to chain him to his desk when he gets back though. 😉 
Check back later this week and all should be resolved.  😺

**Comment by ediril** [comment]
Looks like the new nightly build is available and I confirmed that the problem I reported is now fixed, thank you!

I also confirmed that the problem reported by @chrisjlocke is still present. That is, when a database is closed and reopened (or a different one, the file doesn't matter), all the toolbar buttons are enabled, like "Modify Table" even though I don't have any tables selected yet.
