### ISSUE TITLE
Load extension on MacOS M1 chip

### ISSUE THREAD

**Issue by chris-deep** [sqlitebrowser/sqlitebrowser#3357]
I have an extension I'm trying to load from https://github.com/nalgeon/sqlean.  But, when I use either SELECT load_extension or Tools / Load Extension, I get a file not found error.  Initially the error was "not authorized" so I had to go into Mac system settings / Privacy Security / Allow "math.dylib" to be opened.  

But, I've given myself read write execute permissions to the file and I still can't get it to load in sqlite / DB Browser?

Anyone have any idea how to change permissions for an extension on MacOS so DB Browser can load it?  Thanks!

**Comment by chrisjlocke** [comment]
> I get a file not found error.

Is this still the error?  Looking through other issues, it seems to either suffix the .so or .dylib extension.  

What version of db4s are you using?  I'm not able to tell from the color of the font in your posting.  If you click 'Help' and 'About', a little window dialog thing might appear.  That usually has a lot of info in it, which can be useful.

Can you try running the nightly (if you haven't already .. you might have already, but I can't tell) as the issue might have been fixed.

**Comment by chris-deep** [comment]
Hmm, I tried your suggestion and removed the dylib extension and tried to just load the "math" library.  That didn't work either.  I think somehow it's a system level permissions issue with loading and executing a library from DB4S....

I don't know what else to try or which settings to change at this point.  I loaded DB4S on a Windows VM and got it run and load and execute the extension.  I followed the same steps (download extension, extract files, Load Extension through the UI) and it worked fine on Windows.  But, that's just bc Windows has no real security measures in place on files downloaded from the internet and it just loads and runs the library.

![Screenshot 2023-05-24 at 4 35 57 PM](https://github.com/sqlitebrowser/sqlitebrowser/assets/104459714/5243533c-3dba-4e8f-bed0-132523529bfc)

![Screenshot 2023-05-24 at 4 35 36 PM](https://github.com/sqlitebrowser/sqlitebrowser/assets/104459714/803c8833-e35c-4e73-9b81-5533bf9ba5f6)

**Comment by lucydodo** [comment]
Well, I think it's something to do with macOS Cryptexes.
I've been experiment with a few things to try to resolve it, but I'm not making any progress yet.

For now, why not replace the default bult-in math extension dylib file in the app? Here's the procedure:
1. Right-click on 'DB Browser for SQLite.app'
2. Click 'Show Package Contents' on dropdown menu
3. Go 'Contents' - 'Extensions'
4. Replace 'math.dylib' file with 'nalgeon/sqlean' math dylib file

**Comment by chris-deep** [comment]
Gotcha, thanks.  Makes sense.  I can test that.  As long as DB4S doesn't call any methods other than the LoadExtension then it should work.  So odd that even after I chmod the dylib file I still can't load it though.

**Comment by WebDucer** [comment]
Have same issue. Replacing the lib in application folder also not helped. I wanted to use the stat extension.

I have macOS Sonoma 14.1.1 on MacBook Air M2. DB Browser is in version 3.12.2 (ARM).

**Comment by justinclift** [comment]
@WebDucer Hmmm... would you be ok to try our macOS build from here and see if that works?

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

Asking that because @lucydodo has been reworking the process used for our macOS builds, so there's a decent chance it'll all work ok now.

If it doesn't though, it's something we'll want to investigate and fix... :smile:

**Comment by WebDucer** [comment]
No, unfortunatly, it still not work :/

![Bildschirmfoto 2023-12-01 um 06 56 20](https://github.com/sqlitebrowser/sqlitebrowser/assets/761881/41d45e33-48cc-429f-9774-7aa15075506e)

![Bildschirmfoto 2023-12-01 um 06 59 05](https://github.com/sqlitebrowser/sqlitebrowser/assets/761881/1a0834b8-ecc0-4b21-85ad-a5710bb0d797)

If I can help testing, please reach out to me.

**Comment by WebDucer** [comment]
@justinclift Do we have a "stat" extension already in place? I do not see it the extension folder.

**Comment by justinclift** [comment]
Do you mean the SQLean "stats" one?  If so, then nope we're not yet compiling that as part of our builds.

I mean, we probably *could* add those (and other SQLean ones) but thus far we haven't gotten around to it. :innocent:

**Comment by FotisK** [comment]
I've been following the discussion having the same issue. I tried testing loading the already bundled math.dylib as an extension in the app and also get the error. As for bypassing the expectation of a double .dylib extension, I duplicate the math.dylib file, into a file named math.dylib.dylib an invoke math.dylib. 

this is the built-in math.dylib error
![Screenshot 2023-12-04 at 6 39 56 PM](https://github.com/sqlitebrowser/sqlitebrowser/assets/7896645/4c552f61-a18c-48cd-b7f2-5de266d88b03)

next is the SQLlean text.dylib error
![Screenshot 2023-12-04 at 6 40 11 PM](https://github.com/sqlitebrowser/sqlitebrowser/assets/7896645/819eae09-2b93-4ddd-8a29-0dbc198cf50e)

**Comment by justinclift** [comment]
@FotisK Both of those error messages seem to be cut off before the important info. :frowning:

Actually... if you start the application itself from the terminal window, then it can sometimes print out useful info on that terminal window if it hits errors.

Maybe try that?  aka try running the application from the command line, then loading both of those files.  Hopefully that'll get them to display the full error message text. :smile:

**Comment by lucydodo** [comment]
Hi @FotisK, May I know the system environment what you use? When I tested it on my Mac,
I was able to load built-in `math.dydlib` normally. (DB Browser for SQLCipher Nightly with macOS Sonoma 14.0 23A344)

**Comment by lucydodo** [comment]
I'm not sure, but my guess is that the reason can't load other extension is due to strict code signing.
Or it could be due to other security policies in macOS. (ex: Cryptexes) Let me take a look at this.

**Comment by lucydodo** [comment]
It was solved the issue by turning off 'strict code signing'. but it's time for me to go to work now though.
So I'll upload a test version sometime tomorrow. Sorry for the wait. :(

**Comment by FotisK** [comment]
sorry for the late reply! I tested launching it from the terminal (the stable, the dev and the cipher version) with the `open` command but there were no errors in the terminal when loading any of the extensions. I think however that console caught it for the SQLean `error	20:41:08.097929+0200	kernel	Library Validation failed: Rejecting '/Applications/DB Browser for SQLite.app/Contents/Extensions/text.dylib.dylib' (Team ID: none, platform: no) for process 'DB Browser for S(77070)' (Team ID: C34AV33YLK, platform: no), reason: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)`

interestingly the built-in math.dylib didn't show anything in the console!
I am on Ventura 13.6.1, M1 16GB

**Comment by lucydodo** [comment]
Good morning. Here's a build for testing. (I've double checked that on my Mac, I'm able to load the extension just fine)
However, there is one issue that needs to be discussed. I've turned off the 'Hardend Runtime' security option to allow users to load external libaries (signed with a different team id or unsigned), but in this case Apple does not allow notarization.

So GateKeeper will block the execution and the user has to right click on the application to open the context menu and then press 'Open' to run it. (https://support.apple.com/guide/security/gatekeeper-and-runtime-protection-sec5599b66df/web)

@justinclift There seem to be roughly two options.
1. Release a separate, non-notarized version to allow users to load external libraries.
2. Include all the SQLite's commonly known extensions and sign our certificate.

## You can download the testing version below
- [DB.Browser.for.SQLite-dev-667a297.dmg](https://nightlies.sqlitebrowser.org/macos-prerelease/DB.Browser.for.SQLite-dev-667a297.dmg)
- [DB.Browser.for.SQLCipher-dev-667a297.dmg](https://nightlies.sqlitebrowser.org/macos-prerelease/DB.Browser.for.SQLCipher-dev-667a297.dmg)

### SHA256SUM
```
11bbf91bc3bfe55d0b0420c01810e799569c74756c362fa8b5a513b659aa8587  DB.Browser.for.SQLCipher-dev-667a297.dmg
fe73b1c71408019740a6a9b6ee2341366c3ef8cc39bd203a2259242e21539255  DB.Browser.for.SQLite-dev-667a297.dmg
```

> Reference: [Apple Developer Documentation - Hardend Runtime](https://developer.apple.com/documentation/security/hardened_runtime)

**Comment by WebDucer** [comment]
Looks good. I could now open the SQLean extensions and use them.

I would suggest to sign the extensions and deliver them with the application (if it is OK for the origin extension creators). It would also simplify the "search" for extensions. For me, it took a long search to find them (on Windows), becuase most of internet sources say, you should compile it by yourself :/

Onether way would be to contact the (at least the SQLean) maintainer and ask them to sign the extensions properly for macOS :)

**Comment by justinclift** [comment]
> Include all the SQLite's commonly known extensions and sign our certificate.

@lucydodo Yeah, that's the direction we'll want to go.  It's been something we've kind of wanted to do for ages, but haven't gotten around to yet.

If the licensing of the extensions is compatible (should be, but we should double check) then it's hopefully just a matter of adjusting our build / packaging scripting to add them.

We could start with macOS first, then look at doing it for Linux & Windows too if that goes well. :smile:

**Comment by WebDucer** [comment]
The delivery with the application will also have another positive effect. Users do not need to cary about updates 😁 , new versions of extensions will be delivered with new application versions.

**Comment by FotisK** [comment]
I've too tested the new build and can verify it's running!

**Comment by justinclift** [comment]
@lucydodo Sure.  As a thought, it's probably best to keep the email short (informal style too), and your English is easily good enough.  But I'm happy to review email before you send it, just to help with your confidence. :smile:

**Comment by WebDucer** [comment]
I use [DeepL Write](https://www.deepl.com/write) and [DeepL](https://www.deepl.com) to check my English letters :)

**Comment by justinclift** [comment]
@lucydodo Actually, we're probably making this harder than it needs to be.  Lets try the easy approach first. :smile:

@nalgeon We're considering bundling your `sqlean` extensions with our application, as that'll help our users on macOS.  The `sqlean` GitHub repo says it's MIT licensed so sounds like licensing should be ok.

Do you reckon there are other things or gotcha's that we should be aware of? :smile:

**Comment by nalgeon** [comment]
Hi Justin! I'd love to see these extensions in DB4S. 

The `sqlean` project itself (i.e. the code written by me and the contributors) is MIT licensed. Third-party code used in the extensions is often under different licenses, but only the permissive ones (I check this before including third-party code). You can see all third-party code licenses [in the docs](https://github.com/nalgeon/sqlean/blob/main/docs/third-party.md).

All in all, I believe there are no legal issues preventing you from bundling them with DB4S.

**Comment by lucydodo** [comment]
@nalgeon Thank you, this is great news! 😄 

@justinclift Yes, I'll test it out this weekend and let you know 😄

**Comment by lucydodo** [comment]
@justinclift Just a random thought. `sqlean` is provides precompiled bundle files. Would it make sense for our CI workflow to get the latest precompiled bundle? Or should we let them get the code and build it themselves?

**Comment by justinclift** [comment]
@lucydodo No real preference here.  Try the latest precompiled bundle first I guess, as that'll probably save on your development time.  If that doesn't work though, then we might need to build things ourselves. :smile:

**Comment by lucydodo** [comment]
I'm working on it now, and I have one question. Didn't we originally load the built-in extensions automatically?
I thought they were supposed to load automatically, but am I remembering wrong?
> I mean the built-in extensions are fileio, formats, math

**Comment by justinclift** [comment]
Not sure, personally I don't remember. :shrug:

**Comment by lucydodo** [comment]
Seeing as it doesn't autolaod on Windows builds either, I guess I was wrong.

**Comment by justinclift** [comment]
In theory, the macOS builds here should now have a working `sqlean` extension included:

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

Anyone want to try it out and check? :smile:

**Comment by chris-deep** [comment]
> In theory, the macOS builds here should now have a working `sqlean` extension included:
> 
> https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous
> 
> Anyone want to try it out and check? 😄

Hi, although I started this thread, I'm new to DB4S and sqlite.  So, I need some noob help with testing.  I downloaded the test build and have it running and did the following:

- Create a simple test DB
- Then executed loading extension statement: 
 `select load_extension("/Applications/DB Browser for SQLite-dev-96686a7.app/Contents/Extensions/sqlean.dylib")`
- This gives me:
`Execution finished without errors.
Result: 0 rows returned in 8ms
At line 1:
select load_extension("/Applications/DB Browser for SQLite-dev-96686a7.app/Contents/Extensions/sqlean.dylib")`
- I then run the following:
`select text_substring('hello world', 7);`

And then I get an error:
`Execution finished with errors.
Result: no such function: text_substring
At line 1:
select text_substring('hello world', 7);`

Not sure what I'm doing wrong...?  Sorry, lmk if you can help me test this correctly.  Thanks for all the work getting this build updated!!

**Comment by lucydodo** [comment]
Hi @chris-deep, Make sure the following options are enabled (the default is disabled)
- Preferences - Extensions - Allow loading extensions from SQL code

Since enabling that option, it has worked fine on my Mac.
Alternatively, you can use GUI elmeents to load the `sqlean` extension: https://www.youtube.com/watch?v=FM5TSX9JRA8
<img width="1739" alt="Screenshot 2023-12-10 at 07 30 58" src="https://github.com/sqlitebrowser/sqlitebrowser/assets/64626662/a0cdaa00-24e1-45a7-91ab-9b532a9decba">

**Comment by chris-deep** [comment]
> Hi @chris-deep, Make sure the following options are enabled (the default is disabled)
> 
> * Preferences - Extensions - Allow loading extensions from SQL code
> 
> Since enabling that option, it has worked fine on my Mac. Alternatively, you can use GUI elmeents to load the `sqlean` extension: https://www.youtube.com/watch?v=FM5TSX9JRA8 <img alt="Screenshot 2023-12-10 at 07 30 58" width="1739" src="https://private-user-images.githubusercontent.com/64626662/289315832-a0cdaa00-24e1-45a7-91ab-9b532a9decba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNjE0OTUsIm5iZiI6MTcwMjE2MTE5NSwicGF0aCI6Ii82NDYyNjY2Mi8yODkzMTU4MzItYTBjZGFhMDAtMjRlMS00NWE3LTkxYWItOWI1MzJhOWRlY2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDIyMzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNDYwYjRmOWFiY2EyZmIxZTY5NmU2YTRhNGQ0ZDRlMDY3OWVlNGU2ZDZkNDg1NjIxM2U1N2JjZmIwY2M2YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HHAXSVyWHpJmgUIPQBegwhmizVHrR1rnPyNjqorNbFw">

THANK YOU!!!!!  Works perfectly...  MBPro M1, 16GB, Sonoma 14.1.2

**Comment by lucydodo** [comment]
Glad to hear it's working. this issue seems to be resolved now, so let's close it.
Anyone is welcome to elave additional comments if needed. :)

**Comment by justinclift** [comment]
Fantastic!  You're doing great stuff @lucydodo. :grin:

Wonder if we can get this into the upcoming 3.13.x series releases?  We should probably try to do so if its not super hard.

**Comment by lucydodo** [comment]
I think we have enough to include it. :)
But in the long run, it would be nice to give the user the option to have it loaded automatially.

**Comment by WebDucer** [comment]
Yes, possibility, to load them automatically would be nice. It is for "normal" users not easy to select something from the "App" folder :) macOS do it as uncomfortable as possible.

**Comment by lucydodo** [comment]
Yes, I will implemnt it, but it's the end of the year and I have some personal stuff going on.
Thanks for your understanding, and I'll be sure to update here when it's implemented.

As a note, until this is implemented, if you use the `sqlean` extension frequently, you can set it to load automatically by adding the `sqlean` extension file in DB4S preferences as shown below. :)
<img width="868" alt="Screenshot 2023-12-15 at 15 57 32" src="https://github.com/sqlitebrowser/sqlitebrowser/assets/64626662/4f51b450-2252-4102-9bf4-b1675e7ca4b0">

**Comment by WebDucer** [comment]
No worry. It is Open Source and developed in your free time :)

Would also help coding, but C++ (and macOS) is the language that I don't know well.

**Comment by lucydodo** [comment]
<img width="868" alt="Screenshot 2023-12-30 at 01 05 39" src="https://github.com/sqlitebrowser/sqlitebrowser/assets/64626662/30d8dc94-e0e3-49e0-b2c6-19d19c77a646">

I've added an option to automatically load the `sqlean` extension when loading the DB, which is currently under code review.
Code review progress can be found in the following PR: #3541

**Before the code is reflected in the `master` branch, you can download a build for testing here:** https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/83649a3-3357
If you have any other comments onthe changes, please feel free to let us know. Thank you. :)
