### ISSUE TITLE
Update the Linux build instructions to use qmake

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#832]
It's been pointed out in private email that CMake is broken for our 3.9.1 tarball builds, while qmake still works fine.

We might as well update the Linux compile instructions in BUILDING.md for Qt5 and qmake.

**Comment by justinclift** [comment]
Getting this done will probably address #803 too.

**Comment by leventelist** [comment]
...and if you could include  package dependencies for a generic Linux system to use QT5, that would be nice too. It now insists on using QT4. This is just a wish.

Thanks,
Lev

**Comment by justinclift** [comment]
Ahhh, interesting.  We're just about to switch to Qt5-only, so we'd better get that fixed sooner rather than later. :smile:

**Comment by leventelist** [comment]
Okay. I was too fast typing that wish. I read the documentation again, and there is a package list there. After installing those, it does build fine using GT5. I'm so sorry about the former message.

**Comment by justinclift** [comment]
Cool, no worries at all. :smile:

**Comment by ergovia-mobile** [comment]
An documentation update would be very much welcome. I tried to build sqlitebrowser with sqlcipher support longer that I liked using [building.md](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md) on a (K)ubuntu 16.04.1. I could not build the master no matter what I used (cmake, make, qmake -> _/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:103:5: error: no matching function for call to ‘qHash(const QVector<QSharedPointer<sqlb::Field> >&)’_)._ The only combination that worked was to use the v3.9.1 Tag, install _qt4-default_ and use _qmake CONFIG+=sqlcipher ._ and then _make_.
Once built sqlitebrowser works flawlessly! Thx for this awesome tool.

**Comment by justinclift** [comment]
@ergovia-mobile Interesting.  Was that just now?

I got things to compile on Ubuntu MATE 16.10 yesterday using these steps:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/issues/920#issuecomment-270742689

Maybe I should spin up a VM and go through the steps again... 😁

**Comment by ergovia-mobile** [comment]
Jepp, just now. :)

**Comment by justinclift** [comment]
Cool.  I still have the VM, so I'll try it out now. :smile:

**Comment by ergovia-mobile** [comment]
Thank you. Good luck!

**Comment by justinclift** [comment]
k, just update the VM I was using yesterday with our very latest source code.

It compiled without issue, so that's good news.

I'm downloading Kubuntu 16.0.4.1 now.  I'll put that in a VM and try out the steps from yesterday on it, and see if I can figure out a proper build process for updating our instructions with. :smile:

**Comment by ergovia-mobile** [comment]
That's interesting. Feel free to ask the version number of an package that I have installed. :smile:

**Comment by justinclift** [comment]
Kubuntu looks interesting.  I'm not personally tried KDE in many years (since 3.x?), so this seems like a very polished experience.  Seems like that team has gone in a good direction (unlike my personal opinion of the Gnome team). :wink:

**Comment by ergovia-mobile** [comment]
Totally agree. KDE was glorious in the 3.x days. It hat a pretty rough time in the beginning of the 4.x versions but now it's pretty good looking **and** stable :smile:

**Comment by justinclift** [comment]
Yep, the existing (CMake) build instructions are failing for me in a new Kubuntu 16.0.4.1 VM:

```
[ 88%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/sqlitetypes.cpp.o
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:74:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QString:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:7,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h: In instantiation of ‘uint qHash(const T&, uint) [with T = QVector<QSharedPointer<sqlb::Field> >; uint = unsigned int]’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:952:18:   required from ‘QHash<Key, T>::Node** QHash<Key, T>::findNode(const Key&, uint*) const [with Key = QVector<QSharedPointer<sqlb::Field> >; T = QSharedPointer<sqlb::Constraint>; QHash<Key, T>::Node = QHashNode<QVector<QSharedPointer<sqlb::Field> >, QSharedPointer<sqlb::Constraint> >; uint = unsigned int]’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:758:27:   required from ‘QList<T> QHash<Key, T>::values(const Key&) const [with Key = QVector<QSharedPointer<sqlb::Field> >; T = QSharedPointer<sqlb::Constraint>]’
/home/jc/sqlitebrowser/src/sqlitetypes.cpp:364:44:   required from here
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:103:5: error: no matching function for call to ‘qHash(const QVector<QSharedPointer<sqlb::Field> >&)’
     Q_DECL_NOEXCEPT_EXPR(noexcept(qHash(t)))
     ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h:39:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h:39,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QSharedPointer:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:8,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:65:52: note: candidate: constexpr uint qHash(char, uint)
 Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline uint qHash(char key, uint seed = 0) Q_DECL_NOTHROW { return uint(key) ^ seed; }
                                                    ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:65:52: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘char’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:66:52: note: candidate: constexpr uint qHash(uchar, uint)
 Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline uint qHash(uchar key, uint seed = 0) Q_DECL_NOTHROW { return uint(key) ^ seed; }
                                                    ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:66:52: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘uchar {aka unsigned char}’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:67:52: note: candidate: constexpr uint qHash(signed char, uint)
 Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline uint qHash(signed char key, uint seed = 0) Q_DECL_NOTHROW { return uint(key) ^ seed; }
                                                    ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:67:52: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘signed char’
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h:39:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h:39,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QSharedPointer:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:8,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:68:52: note: candidate: constexpr uint qHash(ushort, uint)
 Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline uint qHash(ushort key, uint seed = 0) Q_DECL_NOTHROW { return uint(key) ^ seed; }
                                                    ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:68:52: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘ushort {aka short unsigned int}’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:69:52: note: candidate: constexpr uint qHash(short int, uint)
 Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline uint qHash(short key, uint seed = 0) Q_DECL_NOTHROW { return uint(key) ^ seed; }
                                                    ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:69:52: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘short int’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:70:52: note: candidate: constexpr uint qHash(uint, uint)
 Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline uint qHash(uint key, uint seed = 0) Q_DECL_NOTHROW { return key ^ seed; }
                                                    ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:70:52: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘uint {aka unsigned int}’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:71:52: note: candidate: constexpr uint qHash(int, uint)
 Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline uint qHash(int key, uint seed = 0) Q_DECL_NOTHROW { return uint(key) ^ seed; }
                                                    ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:71:52: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘int’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:72:52: note: candidate: constexpr uint qHash(ulong, uint)
 Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline uint qHash(ulong key, uint seed = 0) Q_DECL_NOTHROW
                                                    ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:72:52: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘ulong {aka long unsigned int}’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:78:52: note: candidate: constexpr uint qHash(long int, uint)
 Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline uint qHash(long key, uint seed = 0) Q_DECL_NOTHROW { return qHash(ulong(key), seed); }
                                                    ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:78:52: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘long int’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:79:52: note: candidate: constexpr uint qHash(quint64, uint)
 Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline uint qHash(quint64 key, uint seed = 0) Q_DECL_NOTHROW
                                                    ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:79:52: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘quint64 {aka long long unsigned int}’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:83:52: note: candidate: constexpr uint qHash(qint64, uint)
 Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline uint qHash(qint64 key, uint seed = 0) Q_DECL_NOTHROW { return qHash(quint64(key), seed); }
                                                    ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:83:52: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘qint64 {aka long long int}’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:84:42: note: candidate: uint qHash(float, uint)
 Q_CORE_EXPORT Q_DECL_CONST_FUNCTION uint qHash(float key, uint seed = 0) Q_DECL_NOTHROW;
                                          ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:84:42: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘float’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:85:42: note: candidate: uint qHash(double, uint)
 Q_CORE_EXPORT Q_DECL_CONST_FUNCTION uint qHash(double key, uint seed = 0) Q_DECL_NOTHROW;
                                          ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:85:42: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘double’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:87:42: note: candidate: uint qHash(long double, uint)
 Q_CORE_EXPORT Q_DECL_CONST_FUNCTION uint qHash(long double key, uint seed = 0) Q_DECL_NOTHROW;
                                          ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:87:42: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘long double’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:89:52: note: candidate: constexpr uint qHash(QChar, uint)
 Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline uint qHash(const QChar key, uint seed = 0) Q_DECL_NOTHROW { return qHash(key.unicode(), seed); }
                                                    ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:89:52: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘QChar’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:90:41: note: candidate: uint qHash(const QByteArray&, uint)
 Q_CORE_EXPORT Q_DECL_PURE_FUNCTION uint qHash(const QByteArray &key, uint seed = 0) Q_DECL_NOTHROW;
                                         ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:90:41: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘const QByteArray&’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:91:41: note: candidate: uint qHash(const QString&, uint)
 Q_CORE_EXPORT Q_DECL_PURE_FUNCTION uint qHash(const QString &key, uint seed = 0) Q_DECL_NOTHROW;
                                         ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:91:41: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘const QString&’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:92:41: note: candidate: uint qHash(const QStringRef&, uint)
 Q_CORE_EXPORT Q_DECL_PURE_FUNCTION uint qHash(const QStringRef &key, uint seed = 0) Q_DECL_NOTHROW;
                                         ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:92:41: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘const QStringRef&’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:93:41: note: candidate: uint qHash(const QBitArray&, uint)
 Q_CORE_EXPORT Q_DECL_PURE_FUNCTION uint qHash(const QBitArray &key, uint seed = 0) Q_DECL_NOTHROW;
                                         ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:93:41: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘const QBitArray&’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:94:41: note: candidate: uint qHash(QLatin1String, uint)
 Q_CORE_EXPORT Q_DECL_PURE_FUNCTION uint qHash(QLatin1String key, uint seed = 0) Q_DECL_NOTHROW;
                                         ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:94:41: note:   no known conversion for argument 1 from ‘const QVector<QSharedPointer<sqlb::Field> >’ to ‘QLatin1String’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:98:32: note: candidate: template<class T> uint qHash(const T*, uint)
 template <class T> inline uint qHash(const T *key, uint seed = 0) Q_DECL_NOTHROW
                                ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:98:32: note:   template argument deduction/substitution failed:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:74:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QString:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:7,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:103:5: note:   mismatched types ‘const T*’ and ‘QVector<QSharedPointer<sqlb::Field> >’
     Q_DECL_NOEXCEPT_EXPR(noexcept(qHash(t)))
     ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h:45:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QDebug:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:6:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h:241:6: note: candidate: template<class T> uint qHash(const QSet<T>&, uint)
 uint qHash(const QSet<T> &key, uint seed = 0)
      ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h:241:6: note:   template argument deduction/substitution failed:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:74:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QString:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:7,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:103:5: note:   ‘const QVector<QSharedPointer<sqlb::Field> >’ is not derived from ‘const QSet<T>’
     Q_DECL_NOEXCEPT_EXPR(noexcept(qHash(t)))
     ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h:42:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QSharedPointer:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:8,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h:834:24: note: candidate: template<class T> uint qHash(const QSharedPointer<T>&, uint)
 Q_INLINE_TEMPLATE uint qHash(const QSharedPointer<T> &ptr, uint seed = 0)
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h:834:24: note:   template argument deduction/substitution failed:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:74:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QString:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:7,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:103:5: note:   ‘const QVector<QSharedPointer<sqlb::Field> >’ is not derived from ‘const QSharedPointer<T>’
     Q_DECL_NOEXCEPT_EXPR(noexcept(qHash(t)))
     ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h:39:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QSharedPointer:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:8,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h:283:24: note: candidate: template<class T> uint qHash(const QExplicitlySharedDataPointer<T>&, uint)
 Q_INLINE_TEMPLATE uint qHash(const QExplicitlySharedDataPointer<T> &ptr, uint seed = 0) Q_DECL_NOTHROW
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h:283:24: note:   template argument deduction/substitution failed:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:74:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QString:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:7,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:103:5: note:   ‘const QVector<QSharedPointer<sqlb::Field> >’ is not derived from ‘const QExplicitlySharedDataPointer<T>’
     Q_DECL_NOEXCEPT_EXPR(noexcept(qHash(t)))
     ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h:39:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QSharedPointer:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:8,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h:278:24: note: candidate: template<class T> uint qHash(const QSharedDataPointer<T>&, uint)
 Q_INLINE_TEMPLATE uint qHash(const QSharedDataPointer<T> &ptr, uint seed = 0) Q_DECL_NOTHROW
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h:278:24: note:   template argument deduction/substitution failed:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:74:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QString:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:7,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:103:5: note:   ‘const QVector<QSharedPointer<sqlb::Field> >’ is not derived from ‘const QSharedDataPointer<T>’
     Q_DECL_NOEXCEPT_EXPR(noexcept(qHash(t)))
     ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h:39:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h:39,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QSharedPointer:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:8,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:144:49: note: candidate: template<class T1, class T2> uint qHash(const QPair<T1, T2>&, uint)
 template <typename T1, typename T2> inline uint qHash(const QPair<T1, T2> &key, uint seed = 0)
                                                 ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:144:49: note:   template argument deduction/substitution failed:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:74:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QString:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:7,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:103:5: note:   ‘const QVector<QSharedPointer<sqlb::Field> >’ is not derived from ‘const QPair<T1, T2>’
     Q_DECL_NOEXCEPT_EXPR(noexcept(qHash(t)))
     ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h:39:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h:39,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QSharedPointer:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:8,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:102:34: note: candidate: template<class T> uint qHash(const T&, uint)
 template<typename T> inline uint qHash(const T &t, uint seed)
                                  ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:102:34: note:   template argument deduction/substitution failed:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:74:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QString:1,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.h:7,
                 from /home/jc/sqlitebrowser/src/sqlitetypes.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:103:5: note:   candidate expects 2 arguments, 1 provided
     Q_DECL_NOEXCEPT_EXPR(noexcept(qHash(t)))
     ^
CMakeFiles/sqlitebrowser.dir/build.make:606: recipe for target 'CMakeFiles/sqlitebrowser.dir/src/sqlitetypes.cpp.o' failed
make[2]: *** [CMakeFiles/sqlitebrowser.dir/src/sqlitetypes.cpp.o] Error 1
CMakeFiles/Makefile2:71: recipe for target 'CMakeFiles/sqlitebrowser.dir/all' failed
make[1]: *** [CMakeFiles/sqlitebrowser.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

Next step, try with qmake instead.

**Comment by justinclift** [comment]
Same message with the version of qmake installed from the Kubuntu repos.  The error line in the message seems to be:

    /usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:103:5: error: no matching function for call to ‘qHash(const QVector<QSharedPointer<sqlb::Field> >&)’
     Q_DECL_NOEXCEPT_EXPR(noexcept(qHash(t)))

Maybe there's a C++11 setting not being picked up?

I'll try with the latest Qt (from qt.io), and see if that makes a difference.

**Comment by MKleusberg** [comment]
Looks like this function is missing: https://doc.qt.io/qt-5/qvector.html#qHash
The documentation says it's introduced in Qt 5.6, so I assume Kubuntu 16.04 ships an older version?

**Comment by justinclift** [comment]
Yep, seems to be Qt 5.5.1.

**Comment by justinclift** [comment]
@MKleusberg What do you reckon the right approach here is?  Should we declare ourselves to be Qt 5.6 (and above) only, or should we consider alternative approaches to making the code work with older Qt5?

I'm kind of thinking Qt 5.6 and above is probably ok.  The existing "long life" distributions (eg *buntu LTS, CentOS/RHEL) will be providing older builds of DB4S anyway.  Anyone wanting to build the latest code can *probably* download Qt?

**Comment by justinclift** [comment]
Well, this is interesting.  It's impossible to download the Qt 5.7.1 release *without* getting Qt Creator forcibly installed as well.

What kind of sleazy bullshit from the Qt team is that? ☹️

**Comment by justinclift** [comment]
@ergovia-mobile If you download Qt 5.7.1 from qt.io, then compile through Qt Creator (open the sqlitebrowser.pro file with it), things compile fine.

Haven't managed to get it compiling from the command line though, and I need to move onto some other stuff.

Are you ok to try the newer Qt approach?

**Comment by MKleusberg** [comment]
I think Kubuntu 16.04 uses Qt 5.5, correct?
In this case we could try this:
1) Open ```src/sqlitetypes.h```
2) After line 9 (```#include <QVector>```) add a new, empty line and insert this:
```c++
template <typename T>
uint qHash(const QVector<T> &key, uint seed = 0)
    Q_DECL_NOEXCEPT_EXPR(noexcept(qHashRange(key.cbegin(), key.cend(), seed)))
{
    return qHashRange(key.cbegin(), key.cend(), seed);
}
```
3) Try to recompile. Does it compile now? If yes, are table constraints working? If not, has the error message changed?

Maybe we can add this one function and get the minimum Qt version required down to 5.5.

**Comment by ergovia-mobile** [comment]
Yes, my Kubuntu uses Qt 5.5.1. I got a blackscreen on my machine this morning. After a lot of hassel a reinstallation of KDE fixed things. So much for stable :smile: Maybe the Qt Up- and Downgrades messed things up. Dunno....
I am totally fine using v3.9.1 and thinks it is the best/easiest solution if you declare yourself to be Qt 5.6 (and above) only. Just updated build-docs and everybody is happy :smiley:

**Comment by MKleusberg** [comment]
Just added a comment about Qt 5.6 and C++11 to the BUILDING.md file :smiley:

@justinclift What do you reckon, can we leave it like this? Or do we need to suggest using qmake instead of cmake as well? I'm not entirely sure if cmake is still broken and/or on what systems it's broken.

**Comment by justinclift** [comment]
Oops.  Just added this to my ToDo list for investigating this week.

I'll try it out probably Saturday and see if we can make it work with Qt 5.5. :smile:

**Comment by frispete** [comment]
Guys, cmake is broken at the moment.

After struggling an hour to get 3.9.1 build with cmake, I found this issue, and switched to qmake.
FWIW, my builds are public: https://build.opensuse.org/package/show/home:frispete:PyQt5/sqlitebrowser

The problem with cmake starts with the first line of CMakeLists.txt:
`project("DB Browser for SQLite")`

Urgh, blanks in projects name. We all know, that build systems are troublemakers, but this is just a way to **beg** for it... ;)

Next hurdle is missing `C++11` support, that is needed by newer Qt versions.
Fixed this by adding:
`set(CMAKE_CXX_FLAGS "-std=c++11" CACHE STRING "compile flags" FORCE)`
to CMakeLists.txt.

Next, it generated gems like this in `CMakeFiles/DB Browser for SQLite.dir/build.make`:
```
# Object files for target DB Browser for SQLite
DB Browser for SQLite_OBJECTS = \
"CMakeFiles/DB Browser for SQLite.dir/src/AboutDialog.cpp.o" \
```
Note the macro name. Guess, what make says to such expressions... <spit>
Fixed it with a sed script.

After that, I realized, that you creates files, based on this name:
```
if(UNIX AND NOT APPLE)
        install(FILES src/icons/${PROJECT_NAME}.png
                DESTINATION share/icons/hicolor/256x256/apps/)

        install(FILES distri/${PROJECT_NAME}.desktop
                DESTINATION share/applications/)

        install(FILES distri/${PROJECT_NAME}.desktop.appdata.xml
                DESTINATION share/appdata/)
```

At this point, I went to qmake, which got it to build at least, and *thankfully* kept the old, but sane name. 

I still have a few things, that I don't like: the build system should allow to use the platform qscintilla lib. I tried that with qmake, but failed, since openSUSE uses -lqscintilla2-qt5 to distinguish it from qt4 builds, and qmake just removes -qt5. Oh well..

It's up and running, but...

**Comment by justinclift** [comment]
@frispete Yeah, it's a right PITA at the moment. :wink:

As a thought, have you tried building from our master branch instead of the tarball?  Some of the problems should be fixed there, though not all. 😦

**Comment by leventelist** [comment]
I think it is not cmake what is broken. It is sqlitebrowser that miss uses
cmake. Correct?

**Comment by frispete** [comment]
@justinclift Well, to be honest, I'm glad to have it running "nearly" current. The rename of the binary and all is a real PITA for packagers like me. So even with cmake fixed, I'm inclined to keep the qmake build, because I'm lazy, and sqlitebrowser would be the very first app, that contain spaces in the name (we only have a few thousand other binaries @openSUSE...). Be assured, that this will lead to headaches for about every Linux packager of your package out there. 

It's not a question of "if it breaks", it's a question of where. 

@leventelist: I don't think, that cmake is a beautiful piece of software, but as noted before, the project name alone is a receipt for trouble. You can call your program as you like, but I would refrain from using any spaces in it, at least not in those parts, that face a file system.

**Comment by justinclift** [comment]
@frispete No argument here.  Changing the project name in CMakeLists.txt was one of the first things we did after the 3.9.1 release.  It's now only "DB Browser for SQLite" for the OS's which have a need for that (OSX and Windows).

**Comment by frispete** [comment]
@justinclift I see, the CMakeLists.txt looks better now. Let's make a deal, you provide some way of using the system qscintilla, and I test, help to fix the fallout, and push the result to openSUSE official.. 

Hmm the qscintilla version is tweaked, but that is flagged as needed from MacOS only, hence it should be fine. Deal?

**Comment by frispete** [comment]
@justinclift BTW, the separate Qt packages are available here: http://download.qt.io/official_releases/qt/5.7/5.7.1/submodules/

**Comment by justinclift** [comment]
@MKleusberg @innermous Any interest in getting the system provided QScintilla picked up?

I rarely use Linux (more into OSX, BSD), so it's not something I personally care about atm. :smile:

**Comment by frispete** [comment]
Good news for [openSUSE:](https://build.opensuse.org/request/show/451660) 
```
Visit https://build.opensuse.org/request/show/451660

State of request 451660 was changed by pluskalm:

  new -> accepted

Comment:
  thanks

Actions:
- submit home:frispete:PyQt5/sqlitebrowser => server:database/sqlitebrowser
```

**Comment by MKleusberg** [comment]
@justinclift I hate that cmake file. But I will have a look at it, maybe even this evening.
So it's a deal, @frispete :wink:

**Comment by MKleusberg** [comment]
Ugh, the libscintilla2-dev package in Debian (and Ubuntu) is still built against Qt4. So unfortunately I can't test this that easily.

@frispete I've just pushed a largely untested commit which *might* work on openSUSE. Feel free to give it a try :smiley:

**Comment by baksosapi** [comment]
OPENSUSE :

`sid@linux-tfej:~/Downloads/sqlitebrowser-3.9.1> sudo make install
root's password:
cd libs/antlr-2.7.7/ && make -f Makefile.antlr install
make[1]: Entering directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/antlr-2.7.7'
make -f Makefile.antlr.Release install
make[2]: Entering directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/antlr-2.7.7'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/antlr-2.7.7'
make[1]: Leaving directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/antlr-2.7.7'
cd libs/qhexedit/ && make -f Makefile install
make[1]: Entering directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/qhexedit'
make -f Makefile.Release install
make[2]: Entering directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/qhexedit'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/qhexedit'
make[1]: Leaving directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/qhexedit'
cd libs/qcustomplot-source/ && make -f Makefile.qcustomplot install
make[1]: Entering directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/qcustomplot-source'
make -f Makefile.qcustomplot.Release install
make[2]: Entering directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/qcustomplot-source'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/qcustomplot-source'
make[1]: Leaving directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/qcustomplot-source'
cd libs/qscintilla/Qt4Qt5/ && make -f Makefile.qscintilla install
make[1]: Entering directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/qscintilla/Qt4Qt5'
make -f Makefile.qscintilla.Release install
make[2]: Entering directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/qscintilla/Qt4Qt5'
cp -f -r /home/sid/Downloads/sqlitebrowser-3.9.1/libs/qscintilla/Qt4Qt5/Qsci /usr/include/
install -m 644 -p /home/sid/Downloads/sqlitebrowser-3.9.1/libs/qscintilla/Qt4Qt5/qscintilla_cs.qm /usr/share/qt4/translations/
install -m 644 -p /home/sid/Downloads/sqlitebrowser-3.9.1/libs/qscintilla/Qt4Qt5/qscintilla_de.qm /usr/share/qt4/translations/
install -m 644 -p /home/sid/Downloads/sqlitebrowser-3.9.1/libs/qscintilla/Qt4Qt5/qscintilla_es.qm /usr/share/qt4/translations/
install -m 644 -p /home/sid/Downloads/sqlitebrowser-3.9.1/libs/qscintilla/Qt4Qt5/qscintilla_fr.qm /usr/share/qt4/translations/
install -m 644 -p /home/sid/Downloads/sqlitebrowser-3.9.1/libs/qscintilla/Qt4Qt5/qscintilla_pt_br.qm /usr/share/qt4/translations/
install -m 644 -p "libqscintilla2.a" "/usr/lib64/libqscintilla2.a"
install -m 644 -p /home/sid/Downloads/sqlitebrowser-3.9.1/libs/qscintilla/Qt4Qt5/features/qscintilla2.prf /usr/share/qt4//mkspecs/features/
make[2]: Leaving directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/qscintilla/Qt4Qt5'
make[1]: Leaving directory '/home/sid/Downloads/sqlitebrowser-3.9.1/libs/qscintilla/Qt4Qt5'
cd src/ && make -f Makefile install
make[1]: Entering directory '/home/sid/Downloads/sqlitebrowser-3.9.1/src'
make -f Makefile.Release install
make[2]: Entering directory '/home/sid/Downloads/sqlitebrowser-3.9.1/src'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/sid/Downloads/sqlitebrowser-3.9.1/src'
make[1]: Leaving directory '/home/sid/Downloads/sqlitebrowser-3.9.1/src'
`

**Comment by justinclift** [comment]
@frispete Mucking around with getting DB4S to compile on OpenSuSE Leap 42.2:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Notes-for-compiling-on-OpenSuSE-Leap

I've only tried with the CMake version so far.  As @MKleusberg points out, the QScintilla provided by the system isn't functional (for us).  So, even though we can point the compile at it, and it finishes without error... the result segfault immediately on launch:

    $ /usr/local/bin/sqlitebrowser
    Segmentation fault (core dumped)

The CMake variables Martin introduced do work though, so adding `-DFORCE_INTERNAL_QSCINTILLA=ON` to the `cmake` line ensures our version of QScintilla is used.  The resulting executable from that runs fine.  Tested it just now.

Any idea if OpenSuSE is likely to provide a Qt5 version of QScintilla? :smile:

**Comment by justinclift** [comment]
@MKleusberg Your [suggested patch to sqlitetypes.h](https://github.com/sqlitebrowser/sqlitebrowser/issues/832#issuecomment-271159422) works, and lets DB4S build on Ubuntu 16.04.2 again.

Made a proper commit out of it [here](https://github.com/justinclift/sqlitebrowser/commit/c6fbb84773dc11bcc6a60d5e6d67f645068abe0b).

If that patch is your creation and you're happy with it, should we pull it across it across to master "as is"?  If it's a cut-n-paste from the Qt source though, we should at least change it a bit first to avoid licensing problems. :wink:

**Comment by justinclift** [comment]
An alternative that seems to work is installing Qt 5.6 through this PPA first:

&nbsp; &nbsp; https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/stable-phone-overlay

Compiling DB4S works after that, without the above patch.

If the patch approach is workable though, it's probably better as that'd also give us slightly wider compatibility in general (Qt 5.5).

**Comment by MKleusberg** [comment]
@justinclift Hmm, not much to change in these few lines ^^ I've changed the commit to include an ```#if``` in order to not break the build for anybody using Qt 5.6 or later and pushed it to master. If there aren't any more problems, building on Qt 5.5 should work now.

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by leventelist** [comment]
I'm going to test it on Debian stable. I'm afraid that it only has qt5.3.
I'll check later today.

Lev

**Comment by baksosapi** [comment]
I get this 'Segmentation fault' when filled Password field.
I'm already following your step
```
$ cmake -DFORCE_INTERNAL_QSCINTILLA=ON -Dsqlcipher=1
$ make
$ sudo make install
```

but still no luck
Debian Stretch
```
Linux sid-tech 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
```

Any idea?

**Comment by user20190106** [comment]
First of all, many thanks for a great programme!

I found ``DB Browser for SQLite`` when I was searching for a replacement for the Firefox SQLiteManager add-on which is not supported by Firefox any more. And I wish I had found ``DB Browser for SQLite`` earlier.

In particular, the ability to quickly create a plot of the data is really useful. As the zooming feature is not yet included in the released versions, I (after some struggle) managed to build from source - my first ever build!

For someone who has never compiled C programmes earlier, the most difficult part was to figure out what packages needed to be installed.  Therefore I wrote the attached instructions for myself, and I think they  might help other build newbies out there. (I wrote them with Markdown syntax, but the md extension was not allowed for attachments).

[DB_Browser_for_SQLite_build_from_source_on_Debian_Stretch.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/2730495/DB_Browser_for_SQLite_build_from_source_on_Debian_Stretch.txt)

As to the ``QScintilla`` issue, I did not need to use the ``FORCE_INTERNAL_QSCINTILLA=ON`` switch. I guess the changes done relating to [Issue #1555 ](https://github.com/sqlitebrowser/sqlitebrowser/issues/1555) have helped.

Once again, many thanks for a great piece of software,
user20190106

**Comment by mgrojo** [comment]
Thank you, @user20190106. I think your instructions for building under Debian Stretch could be a good contribution to our [wiki](https://github.com/sqlitebrowser/sqlitebrowser/wiki).

**Comment by user20190106** [comment]
@mgrojo,
please feel free to use the text as you wish. Or, as I have done some small edits, can I upload the md file somewhere myself or send it to someone for upload? 

BTW, I also managed to build SQLCipher 4.0.1 with OpenSSL 1.1.0 and then build DB Browser for SQLite using it instead of the standard Debian packages, so I can write an instruction on that as well, if you need one.

However, as reported elsewhere, setting encryption from DB Browser does not work. But using a database that I encrypted with  the  SQLCipher command line interface works.

**Comment by mgrojo** [comment]
>please feel free to use the text as you wish. Or, as I have done some small edits, can I upload the md file somewhere myself or send it to someone for upload?

I think you can use the "New Page" button in the wiki and copy the content of your file there. I'm not sure, but I think all users have permissions to edit the wiki. If that isn't the case, please upload your last version as attachment and I'll copy it to the wiki.

> BTW, I also managed to build SQLCipher 4.0.1 with OpenSSL 1.1.0 and then build DB Browser for SQLite using it instead of the standard Debian packages, so I can write an instruction on that as well, if you need one.

That would also be welcome. Sure some users will find that useful.

> However, as reported elsewhere, setting encryption from DB Browser does not work. But using a database that I encrypted with the SQLCipher command line interface works.

Is that covered in an issue? I couldn't find one.

**Comment by user20190106** [comment]
@mgrojo,
I managed to create 2 new Wiki pages, but I didn't add any links on the main page. I leave it up to the project team.

The issue with encryption not working is [Issue #1690](https://github.com/sqlitebrowser/sqlitebrowser/issues/1690). I added there a comment that I got the same error.

**Comment by mgrojo** [comment]
@user20190106 Thanks again! I've added the necesssary links to your pages to the main page. Great work.

**Comment by MKleusberg** [comment]
I'll close this issue mostly because it is quite old and the original problem seems to be covered by now. Additionally it seems like that Qt6 is moving towards using cmake only anyway.
