### ISSUE TITLE
import sql and begin transaction

### ISSUE THREAD

**Issue by mtissington** [sqlitebrowser/sqlitebrowser#957]
I maybe confused here .. I have an sql file with multiple CREATE TABLEs

BEGIN TRANSACTION;
CREATE TABLE ....
CREATE TABLE ....
CREATE TABLE ....
COMMIT;

One of the CREATE TABLE statements has an error.
When I execute the sql (using Import) I get the error, however the other tables have been created.

Why?

I would expect the entire transaction to be rolled back.

**Comment by MKleusberg** [comment]
Same here as in #955. Should be working with tomorrow's nightly build. Can you download that tomorrow  (or any later day) and check if it's improving things for you? :smiley:

**Comment by mtissington** [comment]
Unfortunately it has made things worse. Now I get a rollback without an error. See the attached.

I think there is still an implied transaction. My sql file has a BEGIN TRANSACTION and COMMIT in it, so a rollback on error is to be expected. However when I remove the transaction I still get the rollback  error which should not happen. If I run the previous build it seems to load the sql just fine (I fixed the errors). But in general this and https://github.com/sqlitebrowser/sqlitebrowser/issues/955 still exist.

![capture](https://cloud.githubusercontent.com/assets/6769116/22510057/6c96990a-e888-11e6-882a-ca991956bd1e.PNG)

**Comment by MKleusberg** [comment]
Hm, sorry about that! I have just made a change which should work around this 'not an error' error. Do you still have the original SQL file causing this error somewhere? And if so can you check again with tomorrow's nightly build? If it still doesn't work it'd be interesting to know what's going on around statement number 30, probably at the end of the file.

**Comment by mtissington** [comment]
OK, will check again tomorrow – thanks.

 

Should I raise another issue, that Import should output to the log I think.

**Comment by MKleusberg** [comment]
Thanks for testing! :smiley:

If you think the import should print to the SQL log feel free to open a new issue for that. The problem here is that unfortunately it's not so easy to do that. When you're importing, say, 100k rows, printing them all to the SQL log would cost way too much performance. But maybe we can discuss a solution for this in a new issue :smiley:

**Comment by mtissington** [comment]
This error still exists and is not fixed (sorry to say)

Please see the attached, the error should be that a CHECK constraint has failed.

[Test.sql.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/748068/Test.sql.txt)

In addition when I remove the BEGIN/COMMIT Transaction statements in the sql, the load is still rolled back. This should not happen. The Load process should follow what is in the sql.
