### ISSUE TITLE
Travis CI build problem

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#962]
Travis CI is failing for our builds at the moment, with this error:

```
$ sudo add-apt-repository ppa:likemartinma/devel -y
$ sudo add-apt-repository --yes ppa:beineri/opt-qt571-trusty
$ sudo apt-get update -qq
W: Failed to fetch http://ppa.launchpad.net/rwky/redis/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

The command "sudo apt-get update -qq" failed and exited with 100 during .

Your build has been stopped.
```

The URL given `/rwky/redis/ubuntu/dists/trusty/main/binary-amd64/Packages` is still returning 404, so this looks like it's not just a transient problem.

Anyone have ideas on what we need to change in order to fix this, or should we attempt to contact the Travis people?

**Comment by MKleusberg** [comment]
Here's somebody else having the same problem: https://github.com/travis-ci/travis-ci/issues/7332
Looks like someone has changed their PPA path and Travis has been relying on it and that's why everyone's builds are now failing :frowning: 

I haven't read the entire discussion on this issue yet but it looks like it might just be fixed by now. Not sure though.

**Comment by justinclift** [comment]
Awesome. :smile:

Reading the comment on that thread, there does seem a decent chance it's resolved.  Plenty of people there saying it's now working for them, although a few "still broken" are happening too.

Guess we'll find out with the next commit. :smile:

**Comment by justinclift** [comment]
Yep, builds are indeed working again. :smile:

**Comment by MKleusberg** [comment]
Awesome :D
